# https://www.playframework.com/documentation/latest/Configuration

# Sets the maximum file size that can be uploaded to 256m.
# https://www.playframework.com/documentation/latest/JavaBodyParsers#Content-length-limits
play.http.parser.maxMemoryBuffer=256m
